AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: One Lambda to rule them all

Resources:

  LambdaOneFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: prime2
      CodeUri: ./
      Handler: main.lambda_handler
      Runtime: python3.8
      Timeout: 3
      MemorySize: 512
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:*
              Resource: arn:aws:logs:*:*:*
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RequestParameters:
              - method.request.querystring.type:
                  Required: true
                  Caching: true

  LogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LambdaOneFunction}'
      RetentionInDays: 7

Outputs:
  LambdaOneApi:
    Description: "Prod stage API Gateway endpoint URL for LambdaOne"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/{function}"
  LambdaOneFunction:
    Description: "LambdaOne Function ARN"
    Value: !GetAtt LambdaOneFunction.Arn
  LambdaOneIamRole:
    Description: "Implicit IAM Role created for LambdaOne"
    Value: !GetAtt LambdaOneFunction.Arn